"use client";

export const VISUALIZER_THEMES = {
  neon: {
    fog: "#07090f",
    roadColor: "#1f2937",
    roadEmissive: "#6d7cff",
    roadEmissiveIntensity: 0.2,
    lineColor: "#6ef3c6",
    riderColor: "#ffffff",
    grid: true,
    stars: true,
    envPreset: "city" as const,
    particleColor: "#4fd1c5",
    skyTop: "#050816",
    skyBottom: "#131b33",
    horizonGlow: "#6d7cff",
    terrainColor: "#0f172a",
    terrainAccent: "#1d4ed8",
    panelColor: "rgba(10, 14, 28, 0.74)",
    worldLabel: "Neon City",
    atmosphere: "grid" as const,
    terrainBackScale: 0.35,
    terrainFrontScale: 0.62,
    patternOpacity: 0.24,
    routeDashOpacity: 0.8,
    props: {
      type: "building" as const,
      color: "#6d7cff",
      count: 40,
      scale: [2, 8, 2] as [number, number, number],
    },
  },
  alpine: {
    fog: "#caccf0",
    roadColor: "#4a5568",
    roadEmissive: "#000000",
    roadEmissiveIntensity: 0,
    lineColor: "#2d3748",
    riderColor: "#fbbf24",
    grid: false,
    stars: false,
    envPreset: "forest" as const,
    particleColor: "#ffffff",
    skyTop: "#b7d3f2",
    skyBottom: "#eaf4ff",
    horizonGlow: "#dbeafe",
    terrainColor: "#25473d",
    terrainAccent: "#84cc16",
    panelColor: "rgba(16, 24, 22, 0.68)",
    worldLabel: "Summit Pass",
    atmosphere: "mist" as const,
    terrainBackScale: 0.48,
    terrainFrontScale: 0.76,
    patternOpacity: 0.08,
    routeDashOpacity: 0.36,
    props: {
      type: "tree" as const,
      color: "#22543d",
      count: 120,
      scale: [0.5, 2, 0.5] as [number, number, number],
    },
  },
  mars: {
    fog: "#451a1a",
    roadColor: "#7f1d1d",
    roadEmissive: "#ef4444",
    roadEmissiveIntensity: 0.1,
    lineColor: "#fca5a5",
    riderColor: "#fbbf24",
    grid: false,
    stars: true,
    envPreset: "sunset" as const,
    particleColor: "#f87171",
    skyTop: "#2b0b0b",
    skyBottom: "#7c2d12",
    horizonGlow: "#fb7185",
    terrainColor: "#4a1d12",
    terrainAccent: "#f97316",
    panelColor: "rgba(28, 10, 8, 0.7)",
    worldLabel: "Red Expanse",
    atmosphere: "dust" as const,
    terrainBackScale: 0.28,
    terrainFrontScale: 0.56,
    patternOpacity: 0.12,
    routeDashOpacity: 0.52,
    props: {
      type: "rock" as const,
      color: "#92400e",
      count: 80,
      scale: [1, 1, 1] as [number, number, number],
    },
  },
  anime: {
    fog: "#ffdeeb",
    roadColor: "#ffffff",
    roadEmissive: "#ff90b3",
    roadEmissiveIntensity: 0.5,
    lineColor: "#ff4d8d",
    riderColor: "#ff4d8d",
    grid: false,
    stars: false,
    envPreset: "apartment" as const,
    particleColor: "#ffc0cb",
    skyTop: "#ffe4f0",
    skyBottom: "#fff9fb",
    horizonGlow: "#ff90b3",
    terrainColor: "#f9a8d4",
    terrainAccent: "#fb7185",
    panelColor: "rgba(88, 28, 62, 0.42)",
    worldLabel: "Toon Valley",
    atmosphere: "sun" as const,
    terrainBackScale: 0.4,
    terrainFrontScale: 0.68,
    patternOpacity: 0.05,
    routeDashOpacity: 0.28,
    props: {
      type: "blossom" as const,
      color: "#fbcfe8",
      count: 200,
      scale: [0.3, 0.3, 0.3] as [number, number, number],
    },
  },
  rainbow: {
    fog: "#1a0b2e",
    roadColor: "#2d1a4a",
    roadEmissive: "#ff00ff",
    roadEmissiveIntensity: 0.8,
    lineColor: "#00ffff",
    riderColor: "#ffffff",
    grid: true,
    stars: true,
    envPreset: "night" as const,
    particleColor: "#ff00ff",
    skyTop: "#130526",
    skyBottom: "#27104c",
    horizonGlow: "#00ffff",
    terrainColor: "#2d1a4a",
    terrainAccent: "#ff00ff",
    panelColor: "rgba(18, 7, 36, 0.72)",
    worldLabel: "Spectrum Run",
    atmosphere: "prism" as const,
    terrainBackScale: 0.32,
    terrainFrontScale: 0.58,
    patternOpacity: 0.18,
    routeDashOpacity: 0.88,
    props: {
      type: "crystal" as const,
      color: "#00ffff",
      count: 60,
      scale: [0.5, 3, 0.5] as [number, number, number],
    },
  },
} as const;

export type VisualizerTheme = keyof typeof VISUALIZER_THEMES;
