[profile.default]
src = "src"
out = "cache/out"
libs = ["node_modules", "lib"]
solc = "0.8.24"
optimizer = true
optimizer_runs = 200
via_ir = true
remappings = [
  "@openzeppelin/=node_modules/@openzeppelin/",
  "forge-std/=lib/forge-std/src/",
  "verifiers/=../verifiers/"
]

[rpc_endpoints]
fuji = "https://api.avax-test.network/ext/bc/C/rpc"

[etherscan]
fuji = { key = "${SNOWTRACE_API_KEY}", url = "https://api.routescan.io/v2/network/testnet/evm/43113/etherscan/api" }
