// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

/**
 * @title MockUltraVerifier
 * @notice Testnet-only mock of the Noir-generated UltraVerifier.
 *
 * The real UltraVerifier is generated by:
 *   1. cd circuits/effort_threshold && bb write_vk -b target/effort_threshold.json -o target/vk
 *   2. bb contract -k target/vk -o contracts/evm/UltraVerifier.sol
 *   See contracts/evm/UltraVerifier.sol for the production stub + full checklist.
 *
 * ⚠️  NEVER deploy this on mainnet — it accepts ANY proof as valid.
 *
 * @custom:security-contact security@spinchain.xyz
 */
contract MockUltraVerifier {
    // ─── Errors ──────────────────────────────────────────────────────────────

    /// @notice Thrown if this contract is somehow deployed on a non-testnet chain.
    error MockNotAllowedOnMainnet();

    // ─── Mainnet guard ───────────────────────────────────────────────────────

    /// @dev Avalanche Mainnet = 43114, Ethereum Mainnet = 1, Sui EVM bridge = reserved.
    ///      Add any additional production chain IDs here.
    function _revertOnMainnet() private view {
        uint256 id = block.chainid;
        if (id == 1 || id == 43114) {
            revert MockNotAllowedOnMainnet();
        }
    }

    // ─── IUltraVerifier ──────────────────────────────────────────────────────

    /**
     * @notice Always returns true on testnets (mock verification).
     * @dev Reverts on Ethereum mainnet (1) and Avalanche mainnet (43114).
     *      The real UltraVerifier signature:
     *        function verify(bytes calldata proof, bytes32[] calldata publicInputs) external view returns (bool)
     */
    function verify(
        bytes calldata, /* proof */
        bytes32[] calldata /* publicInputs */
    ) external view returns (bool) {
        _revertOnMainnet();
        return true;
    }
}
