// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

/**
 * @title IUltraVerifier
 * @notice Interface for the Barretenberg UltraPlonk verifier.
 * @dev Generated by: cd circuits/effort_threshold && bb write_vk && bb contract
 *      Until `bb` is run in CI, this production stub enforces the correct interface
 *      and reverts on uninitialized verification keys — safe for testnet gating.
 */
interface IUltraVerifier {
    function verify(bytes calldata proof, bytes32[] calldata publicInputs) external view returns (bool);
}

/**
 * @title UltraVerifier
 * @notice Production Barretenberg UltraPlonk verifier for the effort_threshold circuit.
 *
 * Deployment checklist (MUST complete before mainnet):
 *   1. Install bb:  curl -L https://raw.githubusercontent.com/AztecProtocol/aztec-packages/master/barretenberg/cpp/installation/install | bash && bbup
 *   2. Generate VK: cd circuits/effort_threshold && bb write_vk -b target/effort_threshold.json -o target/vk
 *   3. Generate contract: bb contract -k target/vk -o ../contracts/evm/UltraVerifier.sol
 *   4. Replace this file with the generated output and redeploy.
 *
 * Until step 4 is complete this contract REVERTS on verify() to prevent
 * accidental acceptance of unverified proofs on any network.
 *
 * @custom:security-contact security@spinchain.xyz
 */
contract UltraVerifier is IUltraVerifier {
    // ─── Errors ──────────────────────────────────────────────────────────────

    /// @notice Thrown when verify() is called before the real VK is embedded.
    error VerificationKeyNotInitialized();

    // ─── State ───────────────────────────────────────────────────────────────

    /// @notice Set to true only after the bb-generated VK bytes are embedded.
    bool public constant VERIFICATION_KEY_INITIALIZED = false;

    // ─── IUltraVerifier ──────────────────────────────────────────────────────

    /**
     * @notice Verify a Barretenberg UltraPlonk proof against the effort_threshold circuit.
     * @dev Reverts until the real bb-generated verifier replaces this file.
     *      The real implementation will inline the verification key and call the
     *      Barretenberg precompile / pure-Solidity verifier logic.
     * @param proof   Serialised UltraPlonk proof bytes.
     * @param publicInputs  Public circuit inputs as bytes32 array.
     * @return true iff the proof is valid (never reached in this stub).
     */
    function verify(
        bytes calldata proof,
        bytes32[] calldata publicInputs
    ) external pure override returns (bool) {
        // Silence unused-parameter warnings while keeping the correct signature.
        proof;
        publicInputs;
        revert VerificationKeyNotInitialized();
    }
}
